rd /s /q "core/cgui/lib"
rd /s /q "core/cofiles/lib"
rd /s /q "core/cctrl/lib"
rd /s /q "core/cguicontrols/lib"
rd /s /q "docs/manual"
rd /s /q "samples/cadventcalendar/build"
rd /s /q "samples/ccontrols/build"
rd /s /q "samples/cctrlhelloworld/build"
rd /s /q "samples/cdragdrop/build"
rd /s /q "samples/cdynamic/build"
rd /s /q "samples/cguihelloworld/build"
rd /s /q "samples/cmadtv/build/common"
del /q "samples/cmadtv/build"\*.*
rd /s /q "samples/cmadtvdata/lib"
rd /s /q "samples/cofileshelloworld/build"
rd /s /q "samples/cpositions/build"
rd /s /q "samples/csizemode/build"
rd /s /q "samples/cxmlparser/build"
rd /s /q "tools/ced/build"
rd /s /q "projects\visualc\cframework\cadventcalendar/Debug"
rd /s /q "projects\visualc\cframework\cadventcalendar/Release"
rd /s /q "projects\visualc\cframework\ccontrols/Debug"
rd /s /q "projects/visualc/cframework/ccontrols/Release"
rd /s /q "projects/visualc/cframework/cctrl/Debug"
rd /s /q "projects/visualc/cframework/cctrl/Hybrid"
rd /s /q "projects/visualc/cframework/cctrl/Release"
rd /s /q "projects/visualc/cframework/cctrlhelloworld/Debug"
rd /s /q "projects/visualc/cframework/cctrlhelloworld/Release"
rd /s /q "projects/visualc/cframework/cdragdrop/Debug"
rd /s /q "projects/visualc/cframework/cdragdrop/Release"
rd /s /q "projects/visualc/cframework/ced/Debug"
rd /s /q "projects/visualc/cframework/ced/Release"
rd /s /q "projects/visualc/cframework/cetris/Debug"
rd /s /q "projects/visualc/cframework/cetris/Release"
rd /s /q "projects/visualc/cframework/cgui/Debug"
rd /s /q "projects/visualc/cframework/cgui/Hybrid"
rd /s /q "projects/visualc/cframework/cgui/Release"
rd /s /q "projects/visualc/cframework/cguicontrols/Debug"
rd /s /q "projects/visualc/cframework/cguicontrols/Hybrid"
rd /s /q "projects/visualc/cframework/cguicontrols/Release"
rd /s /q "projects/visualc/cframework/cguihelloworld/Debug"
rd /s /q "projects/visualc/cframework/cguihelloworld/Release"
rd /s /q "projects/visualc/cframework/cmadtv/Debug"
rd /s /q "projects/visualc/cframework/cmadtv/Hybrid"
rd /s /q "projects/visualc/cframework/cmadtv/Release"
rd /s /q "projects/visualc/cframework/cmadtvdata/Debug"
rd /s /q "projects/visualc/cframework/cmadtvdata/Hybrid"
rd /s /q "projects/visualc/cframework/cmadtvdata/Release"
rd /s /q "projects/visualc/cframework/cofiles/Debug"
rd /s /q "projects/visualc/cframework/cofiles/Hybrid"
rd /s /q "projects/visualc/cframework/cofiles/Release"
rd /s /q "projects/visualc/cframework/cofileshelloworld/Debug"
rd /s /q "projects/visualc/cframework/cofileshelloworld/Hybrid"
rd /s /q "projects/visualc/cframework/cofileshelloworld/Release"
rd /s /q "projects/visualc/cframework/cpositions/Debug"
rd /s /q "projects/visualc/cframework/cpositions/Release"
rd /s /q "projects/visualc/cframework/csizemode/Debug"
rd /s /q "projects/visualc/cframework/csizemode/Release"
rd /s /q "projects/visualc/cframework/csystem/Debug"
rd /s /q "projects/visualc/cframework/csystem/Release"
rd /s /q "projects/visualc/cframework/cxmlparser/Debug"
rd /s /q "projects/visualc/cframework/cxmlparser/Release"
rd /s /q "projects/visualc/cframework/glpng/Debug"
rd /s /q "projects/visualc/cframework/glpng/Release"
del "projects/visualc/cframework"\cframework.ncb
del /a:h "projects/visualc/cframework"\cframework.suo
rd /s /q "projects/eclipse/cgui/Debug"
rd /s /q "projects/eclipse/cgui/Release"
rd /s /q "projects/eclipse/cguihelloworld/Debug"
rd /s /q "projects/eclipse/cguihelloworld/Release"
rd /s /q "projects/eclipse/cofiles/Debug"
rd /s /q "projects/eclipse/cofiles/Release"
rd /s /q "projects/eclipse/cofileshelloworld/Debug"
rd /s /q "projects/eclipse/cofileshelloworld/Release"
rd /s /q "projects/eclipse/glpng/Debug"
rd /s /q "projects/eclipse/glpng/Release"
rd /s /q "projects/eclipse/test/Debug"
rd /s /q "projects/eclipse/test/Release"
rd /s /q "projects/eclipse/.metadata"
rd /s /q "projects/codeblocks/cctrl/obj"
del "projects/codeblocks/cctrl"\*.a
rd /s /q "projects/codeblocks/cctrlhelloworld/obj"
del "projects/codeblocks/cctrlhelloworld"\*.exe
rd /s /q "projects/codeblocks/cgui/obj"
del "projects/codeblocks/cgui"\*.a
rd /s /q "projects/codeblocks/cguihelloworld/bin"
rd /s /q "projects/codeblocks/cguihelloworld/obj"
del "projects/codeblocks/cguihelloworld"\*.exe
rd /s /q "projects/codeblocks/cofiles/obj"
del "projects/codeblocks/cofiles"\*.a
rd /s /q "projects/codeblocks/cofileshelloworld/bin"
rd /s /q "projects/codeblocks/cofileshelloworld/obj"
del "projects/codeblocks/cofileshelloworld"\*.exe
rd /s /q "projects/codeblocks/glpng/obj"
del "projects/codeblocks/glpng"\*.a
pause